name: clean_code_snippets
description: A Flutter project implements uncle bob clean code architecture.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  fluttertoast: ^8.0.9
  equatable: ^2.0.3
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.0.15
  http: ^0.13.4
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/chicken-skewers-with-slices-sweet-peppers-dill.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500